---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ceph-cluster
  namespace: rook-ceph
spec:
  releaseName: ceph-cluster
  chart:
    git: https://github.com/huettner94/k8s-flux.git
    ref: master
    path: charts/rook-cluster
  values:
    pools:
      replicated:
        - name: high
          replicas: 3
        - name: low
          replicas: 2