---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rook
  namespace: rook-ceph
spec:
  releaseName: rook
  chart:
    repository: https://charts.rook.io/release
    name: rook-ceph
    version: v1.3.1
  values:
    csi:
      cephcsi:
        image: quay.io/cephcsi/cephcsi:v2.1.0-arm64
      registrar:
        image: teanan/csi-node-driver-registrar:v1.2.0
      provisioner:
        image: teanan/csi-provisioner:v1.4.0
      snapshotter:
        image: teanan/csi-snapshotter:v1.2.2
      attacher:
        image: teanan/csi-attacher:v2.1.0
