---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: prometheus
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: grafana
    version: 3.12.1
  values:
    image:
      repository: grafana/grafana-arm64v8-linux # Temporary Fix for https://github.com/grafana/grafana/issues/19585
      tag: dev-musl
    persistence:
      enabled: True
      storageClassName: rook-ceph-block-low
    ingress:
      enabled: True
      hosts:
        - grafana.apps.huettner.local
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            isDefault: true
            url: http://prometheus-server.prometheus.svc.cluster.local
    plugins:
      - grafana-piechart-panel
