---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: owncloud
  namespace: owncloud
spec:
  releaseName: owncloud
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: owncloud
    version: 8.1.15
  values:
    global:
      storageClass: rook-ceph-block-high
    image:
      repository: huettner94/bitnami-owncloud
      tag: 10.4.1-debian-10-r3
    ingress:
      enabled: true
      hosts:
        - name: owncloud.apps.huettner.local
    owncloudHost: owncloud.apps.huettner.local
    mariadb:
      enabled: true
      image:
        repository: huettner94/bitnami-mariadb
        tag: 10.4.12-debian-10-r88
