---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: olm
  namespace: olm
spec:
  releaseName: olm
  chart:
    git: https://github.com/operator-framework/operator-lifecycle-manager.git
    ref: 0.12.0
    path: deploy/chart