---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  releaseName: metallb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.12.0
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 10.0.128.20-10.0.128.25
    prometheus:
      scrapeAnnotations: True