---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  releaseName: traefik
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: traefik
    version: 1.78.4
  values:
    rbac:
      enabled: true
    dashboard:
      enabled: true
      domain: traefik.apps.huettner.local
    ssl:
      enabled: true
      generateTLS: true
      defaultCN: apps.huettner.local
      defaultSANList:
        - "*.apps.huettner.local"
      insecureSkipVerify: true
    metrics:
      prometheus:
        enabled: True
    deployment:
      podAnnotations:
        prometheus.io/scrape: true
        prometheus.io/port: 8080